name: 'Extract Issue Template Fields'
description: 'Extract metadata and body from issue template markdown'
branding:
  icon: align-left
  color: white
inputs:
  token:
    description: |-
      Token used to authenticate with GitHub API.
    required: false
    default: ${{ github.token }}
    
  path:
    description: |-
      Full path to template file, e.g. .github/ISSUE_TEMPLATES/bug.md
    required: true

outputs:
  body:
    description: |-
      Body of issue template

  title:
    description: |-
      Title field

  labels:
    description: |-
      Comma delimited list of labels

  assignees:
    description: |-
      Comma delimited list of assignees

runs:
  using: 'node20'
  main: 'dist/index.js'
